# Site settings
title: Minverter Project
author:
  name: DR
  email: info@kalyna.energy
description: "A low-cost open source microinverter (project)"

google_analytics: G-LT3871TRQG
show_excerpts: true
excerpt_separator: <!--more-->


# Build settings
remote_theme: jekyll/minima
include: ["_includes"]
