# Site settings
title: Minverter Project
author:
  name: Doug Ridgway
  email: doug@kalyna.energy
description: "World's best open source microinverter (project)"

google_analytics: G-LT3871TRQG
show_excerpts: true


# Build settings
remote_theme: jekyll/minima
include: ["_includes"]
