# Site settings
title: Minverter Project
author:
  name: DR
  email: info@kalyna.energy
description: "World's worst open source microinverter (project)"

google_analytics: G-LT3871TRQG
show_excerpts: true


# Build settings
remote_theme: jekyll/minima
include: ["_includes"]
